# Generated by Django 3.1.2 on 2020-12-14 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='area_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(default='', max_length=10)),
                ('pincode', models.IntegerField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='category_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(default='', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='contact_us_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=20)),
                ('con_no', models.IntegerField(default=0)),
                ('msg', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='customer_data',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('f_name', models.TextField(default='', max_length=20)),
                ('l_name', models.TextField(default='', max_length=20)),
                ('Email', models.EmailField(default='', max_length=20)),
                ('gender', models.BooleanField(default='', max_length=6)),
                ('image', models.ImageField(upload_to='')),
                ('con_no', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='order_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_date', models.DateField()),
                ('o_amount', models.FloatField(default='')),
                ('o_address', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer_data')),
            ],
        ),
        migrations.CreateModel(
            name='product_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.TextField(default='', max_length=20)),
                ('p_price', models.FloatField(default=0)),
                ('p_desc', models.CharField(default='', max_length=100)),
                ('p_image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='payment_data',
            fields=[
                ('o_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.order_data')),
                ('pay_date', models.DateField()),
                ('pay_status', models.TextField(default='', max_length=15)),
                ('pay_mode', models.TextField(default='', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(default='', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category_data')),
            ],
        ),
        migrations.CreateModel(
            name='review_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default='')),
                ('review', models.CharField(default='', max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer_data')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product_data')),
            ],
        ),
        migrations.AddField(
            model_name='product_data',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.sub_category_data'),
        ),
        migrations.CreateModel(
            name='order_item_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default='')),
                ('amount', models.FloatField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.order_data')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product_data')),
            ],
        ),
        migrations.CreateModel(
            name='gallery_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product_data')),
            ],
        ),
    ]
